media_root: media
media_url: /media
base_url: /
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.combine.CombinePlugin
  - hyde.ext.plugins.languages.LanguagePlugin
  - hyde.ext.plugins.auto_extend.AutoExtendPlugin
  - hyde.ext.plugins.less.LessCSSPlugin
  - hyde.ext.plugins.textlinks.TextlinksPlugin
  - hyde.ext.plugins.optipng.OptiPNGPlugin
  - hyde.ext.plugins.uglify.UglifyPlugin
context:
  data:
    languages:
      fr: Français
      en: English
meta:
  nodemeta: meta.yaml
  author: Vincent Bernat
  language: en
  analytics: UA-21482482-4
  keywords: "debian, python, network, vincent bernat"
less:
  app: /usr/bin/lessc
  args:
    compress: 0
optipng:
  app: /usr/bin/optipng
  args:
    quiet: 0
uglify:
  app: /usr/bin/uglifyjs
markdown:
  extensions:
    - codehilite
