mode: development
media_root: media
media_url: /media
base_url: /
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.git.GitDatesPlugin
  - extensions.combine.CombinePlugin
  - hyde.ext.plugins.languages.LanguagePlugin
  - hyde.ext.plugins.auto_extend.AutoExtendPlugin
  - hyde.ext.plugins.sorter.SorterPlugin
  - hyde.ext.plugins.tagger.TaggerPlugin
  - hyde.ext.plugins.less.LessCSSPlugin
  - hyde.ext.plugins.textlinks.TextlinksPlugin
  - extensions.css.CSSPrefixerPlugin
  - extensions.images.ImageThumbnailsPlugin
  - extensions.images.ImageFixerPlugin
  - extensions.text.LatexPlugin
  - extensions.text.FootnotesPlugin
  - extensions.typo.TypographyPlugin
context:
  data:
    base: https://vincent.bernat.ch
    languages:
      fr: Français
      en: English
meta:
  nodemeta: meta.yaml
  author: Vincent Bernat
  title: "MTU Ninja"
  language: en
  share: true
  tags: [unclassified]
simple_copy:
  - media/videos/**
less:
  app: node_modules/less/bin/lessc
markdown:
  extensions:
    - codehilite
    - extra
    - toc
    - extensions.markdown.admonition
    - extensions.markdown.glyphs
    - extensions.markdown.mathjax
    - extensions.markdown.responsive_table
    - extensions.markdown.codehilite_lang
  extension_configs:
    toc:
      permalink: "\U00002693\U0000fe0e"
      # Also modify it in layout/atom.j2
    extra:
      markdown.extensions.footnotes:
        BACKLINK_TEXT: '&#8617;&#xFE0E;'
  output_format: html5
jinja2:
  filters:
    human_date: extensions.jinja.human_date
    same_tag: extensions.jinja.same_tag
sorter:
  name:
    attr:
      - relative_path
  time:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
  time_fr:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: fr
  time_en:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: en
tagger:
  sorter: time
  tags:
    network:
      descr_en: Network
      descr_fr: Réseau
      order: 10
    network-bgp:
      descr: BGP
      order: 11
    network-vxlan:
      descr: VXLAN
      order: 12
    network-vpn:
      descr: VPN
      order: 13
    network-snmp:
      descr: SNMP
      order: 14
    linux:
      descr: Linux
      order: 20
    programming:
      descr_en: Programming
      descr_fr: Programmation
      order: 30
    programming-go:
      descr: Go
      order: 31
    programming-c:
      descr: C
      order: 32
    programming-python:
      descr: Python
      order: 33
    ssl:
      descr: TLS
      order: 40
    debian:
      descr: Debian
      order: 50
    retro:
      descr_en: Retrocomputing
      descr_fr: Rétrocomputing
      order: 60
    web:
      descr: Web
      order: 70
    desktop:
      descr_en: Desktop
      descr_fr: Bureau
      order: 80
    unclassified:
      descr_en: Unclassified
      descr_fr: Non classé
      order: 999
    outdated:
      descr_en: Outdated
      descr_fr: Archaïque
      order: 1000
