mode: development
media_root: media
media_url: /media
base_url: /
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.git.GitDatesPlugin
  - extensions.combine.CombinePlugin
  - hyde.ext.plugins.languages.LanguagePlugin
  - hyde.ext.plugins.auto_extend.AutoExtendPlugin
  - hyde.ext.plugins.sorter.SorterPlugin
  - hyde.ext.plugins.tagger.TaggerPlugin
  - hyde.ext.plugins.less.LessCSSPlugin
  - hyde.ext.plugins.textlinks.TextlinksPlugin
  - extensions.css.CSSPrefixerPlugin
  - extensions.images.ImageThumbnailsPlugin
  - extensions.images.ImageFixerPlugin
  - extensions.text.LatexPlugin
  - extensions.text.FootnotesPlugin
  - extensions.typo.TypographyPlugin
context:
  data:
    base: https://vincent.bernat.ch
    languages:
      fr: Français
      en: English
meta:
  nodemeta: meta.yaml
  author: Vincent Bernat
  title: "MTU Ninja"
  language: en
simple_copy:
  - media/videos/**
less:
  app: node_modules/less/bin/lessc
markdown:
  extensions:
    - codehilite
    - extra
    - toc
    - extensions.markdown.admonition
    - extensions.markdown.glyphs
    - extensions.markdown.mathjax
    - extensions.markdown.responsive_table
    - extensions.markdown.codehilite_lang
  extension_configs:
    toc:
      permalink: "\U00002693\U0000fe0e"
    extra:
      markdown.extensions.footnotes:
        BACKLINK_TEXT: '&#8617;&#xFE0E;'
  output_format: html5
jinja2:
  filters:
    human_date: extensions.jinja.human_date
    same_tag: extensions.jinja.same_tag
sorter:
  name:
    attr:
      - relative_path
  time:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
  time_fr:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: fr
  time_en:
    attr:
      - meta.created
      - relative_path
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: en
tagger:
  sorter: time
  tags:
    network:
      descr_en: Network
      descr_fr: Réseau
      order: 10
    kernel:
      descr_en: Linux kernel
      descr_fr: Noyau Linux
      order: 11
    ssl:
      descr: TLS
      order: 12
    golang:
      descr: Go
      order: 13
    debian:
      descr: Debian
      order: 14
    retro:
      descr_en: Retrocomputing
      descr_fr: Rétrocomputing
      order: 15
    web:
      descr: Web
      order: 16
    vxlan:
      descr: VXLAN
      order: 20
    snmp:
      descr: SNMP
      order: 21
    desktop:
      descr_en: Desktop
      descr_fr: Bureau
      order: 30
    outdated:
      descr_en: Outdated
      descr_fr: Archaïque
      order: 100
