media_root: media
media_url: /media
base_url: /
plugins:
  - hyde.ext.plugins.meta.MetaPlugin
  - hyde.ext.plugins.git.GitDatesPlugin
  - hyde.ext.plugins.combine.CombinePlugin
  - hyde.ext.plugins.languages.LanguagePlugin
  - hyde.ext.plugins.auto_extend.AutoExtendPlugin
  - hyde.ext.plugins.sorter.SorterPlugin
  - hyde.ext.plugins.less.LessCSSPlugin
  - hyde.ext.plugins.textlinks.TextlinksPlugin
  - hyde.ext.plugins.urls.UrlCleanerPlugin
  - hyde.ext.plugins.optipng.OptiPNGPlugin
  - hyde.ext.plugins.jpegoptim.JPEGOptimPlugin
  - hyde.ext.plugins.images.ImageSizerPlugin
  - hyde.ext.plugins.uglify.UglifyPlugin
context:
  data:
    base: http://www.luffy.cx
    languages:
      fr: Français
      en: English
meta:
  nodemeta: meta.yaml
  author: Vincent Bernat
  title: "Disruptive Ninja"
  created: git
  modified: git
  language: en
  analytics: UA-21482482-4
  disqus: luffycx
  keywords: "debian, python, network, vincent bernat"
less:
  app: /usr/bin/lessc
  args:
    compress: ""
optipng:
  app: /usr/bin/optipng
  args:
    quiet: ""
jpegoptim:
  app: /usr/bin/jpegoptim
  args:
    max: "70"
uglify:
  app: /usr/bin/uglifyjs
markdown:
  extensions:
    - codehilite
    - extra
sorter:
  time_fr:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: fr
  time_en:
    attr:
      - meta.created
    reverse: true
    filters:
      source.kind: html
      meta.listable: true
      meta.language: en
urlcleaner:
  index_file_names:
    - index.html
  append_slash: true
