extends: base.j2
default_block: article

language: fr
created: git
modified: git
menu:
  -
     name: "Projets"
     page: "projets.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  otherlinks: "Autres liens"
  translations: "Aussi disponible en"
  comments_nojs: >-
    Le système de commentaire utilise Disqus qui nécessite Javascript
  comments: >-
    <a href="">Lire ou écrire des commentaires</a> (ils reposent
    sur Disqus et quelques <a class="underlined-link"
    href="https://help.disqus.com/customer/portal/articles/466235-use-of-cookies">cookies</a>)
  subscribe: >-
    S'abonner aux mises à jour
  attachments: "Documents liés"
  tags: "Classé dans"
  share: "Partager cet article"
  share_on: "Partager sur"
  share_by_mail: "Partager par courriel"
