extends: base.j2
default_block: article

language: fr
created: git
modified: git
menu:
  -
     name: "Projets"
     page: "projets.html"
  -
     name: "Blog"
     page: "blog"
l10n:
  otherlinks: "Ailleurs"
  translations: "Aussi disponible en"
  comments_nojs: >-
    Le système de commentaire utilise Isso qui nécessite Javascript
  comments: >-
    <a href="#isso-thread">Commentaires</a> (ils reposent sur <em>Isso</em> et sont sans cookies)
  subscribe: >-
    S’abonner aux mises à jour
  attachments: "Documents liés"
  tags: "Classé dans"
  share: "Partager cet article"
  share_on: "Partager sur"
  share_by_mail: "Partager par courriel"
  range: "-"                    # trait d'union
