extends: base.j2
default_block: article

language: fr
menu:
  -
     name: "Projets"
     page: "projets.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  otherlinks: "Autres liens"
  translations: "Aussi disponible en"
  comments_nojs: >-
    Le système de commentaire utilisé sur ce site est Disqus. Il
    nécessite l'usage de Javascript. Si vous voulez lire ou laisser un
    commentaire, merci d'activer Javascript ou d'essayer avec un
    navigateur différent.
  comments: >-
    Si vous avez apprécié l'article ou si vous avez quelque chose à
    ajouter, pourquoi ne pas laisser un <a href>commentaire</a> ou
    lire ceux des autres ? Le système de commentaires est animé par
    Disqus et requiert l'utilisation de
    <a href="https://help.disqus.com/customer/portal/articles/466235-use-of-cookies">cookies</a>.
  attachments: "Documents liés"
  tags: "Classé dans"
  share: "Partager cet article"
