extends: base.j2
default_block: article

language: en
created: git
modified: git
menu:
  -
     name: "Projects"
     page: "projects.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  otherlinks: "Other stuff"
  translations: "Also available in"
  comments_nojs: >-
    The comment system uses Disqus and requires Javascript
  comments: >-
    <a href="">Read or publish comments</a> (they rely on
    <em>Disqus</em> and some <a
    href="https://help.disqus.com/customer/portal/articles/466235-use-of-cookies">cookies</a>)
  subscribe: >-
    Subscribe to new posts
  attachments: "Attachments"
  tags: "Filed under"
  share: "Share this article"
  share_on: "Share on"
  share_by_mail: "Share by mail"
