extends: base.j2
default_block: main

language: en
menu:
  -
     name: "CV"
     page: "cv.html"
  -
     name: "Projets"
     page: "projets.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  search: "Search"
  otherlinks: "Other stuff"
  translations: "Other languages"
