extends: base.j2
default_block: article

language: en
menu:
  -
     name: "CV"
     page: "cv.html"
  -
     name: "Projects"
     page: "projects.html"
  -
     name: "Blog"
     page: "blog/"
google_cse: "005302691838508801550:am84wi88jr8"
l10n:
  search: "Search"
  otherlinks: "Other stuff"
  translations: "Other languages"
  posts: "Other articles"
  next: "Next"
  previous: "Previous"
  comments: "View or add a new comment"
