extends: base.j2
default_block: article

language: en
menu:
  -
     name: "Projects"
     page: "projects.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  otherlinks: "Other stuff"
  translations: "Also available in"
  comments_nojs: >-
    The comments on this website are powered by Disqus and require the
    use of Javascript. Please enable Javascript or try with a
    different browser.
  comments: >-
    You can <a href="">leave a comment</a> or read others’ ones. The
    comment system is powered by <em>Disqus</em> and its use relies on <a
    href="https://help.disqus.com/customer/portal/articles/466235-use-of-cookies">cookies</a>.
  attachments: "Attachments"
  tags: "Filed under"
  share: "Share this article"
