extends: base.j2
default_block: article

language: en
menu:
  -
     name: "Projects"
     page: "projects.html"
  -
     name: "Blog"
     page: "blog/"
l10n:
  otherlinks: "Other stuff"
  translations: "Also available in"
  comments_nojs: >-
    The comments on this website are powered by Disqus and require the
    use of JavaScript. If you're interested in reading the comments or
    leaving a comment behind please enable Javascript or try with a
    different browser.
  comments: >-
    Did you enjoy the article or do you have anything to add? Why not
    leave a <a href>comment</a> or read others' ones? The comment
    system is powered by Disqus and its use relies on 
    <a href="https://help.disqus.com/customer/portal/articles/466235-use-of-cookies">cookies</a>.
  attachments: "Attachments"
  tags: "Filed under"
  share: "Share this article"
